name: Deploy to production
on:
  release:
    types: [released]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-env:
    name: "Update production environment config"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 #install the python needed
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
      - name: Update .env.local # run file
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SECRET_CONFIG: ${{ secrets.SECRET_CONFIG }}
        run: |
          python update_env.py
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://nsarrazin:$HF_TOKEN@huggingface.co/spaces/huggingchat/chat-ui main
